version: '3.4'

services:
  api:
    container_name: bgapp-api
    build: ../
    env_file: ../.env
    volumes:
      - ..:/app
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - bgapp-network

  postgres:
    container_name: bgapp-postgres
    image: postgres:13-bullseye
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    env_file: ../.env
    ports:
      - "5432:5432"
    networks:
      - bgapp-network

networks:
  bgapp-network: {}

volumes:
  postgres_data_local: {}
