name: Build and push Docker image

on:
  workflow_call:
    secrets:
      username:
        description: 'DockerHub username'
        required: true
      token:
        description: 'DockerHub token'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}
      - name: Build docker image
        run: docker build -t ${{ secrets.username }}/bgapp-api:${{ github.head_ref }} .
      - name: Push docker image
        run: docker push ${{ secrets.username }}/bgapp-api:${{ github.head_ref }}