name: Continuous integration

on:
  pull_request:
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Copy .env from template
        run: cp env.template .env
      - name: Install poetry
        run: pip install poetry==1.1.14
      - name: Install dependencies
        run: poetry install -v
      - name: Check code formatting
        run: poetry run black --check .
      - name: Check code style with flake8
        run:  poetry run flake8 .
      - name: Run unit tests
        run:  poetry run pytest -m unit --cov --cov-branch --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
      - uses: isbang/compose-action@v1.2.0
        with:
          compose-file: ".deployment/docker-compose.yml"
          down-flags: "--volumes"
          services: |
            postgres
      - name: Run integration tests
        run: poetry run pytest -m integration
        env:
          BGAPP__DATABASE__HOST: postgres
