name: Continuous integration

on:
  pull_request:
jobs:
  build:
    uses: ./.github/workflows/build.yml
  build-docker-image:
    uses: ./.github/workflows/build-docker-image.yml
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  lint:
    uses: ./.github/workflows/lint.yml
    needs: build
  unit-test:
    uses: ./.github/workflows/unit-test.yml
    needs: lint
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
  integration-test:
    uses: ./.github/workflows/integration-test.yml
    needs: lint

