name: Upload coverage in master branch

on:
  push:
    branches:
      - master
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Copy .env from template
        run: cp env.template .env
      - name: Install poetry
        run: pip install poetry==1.1.14
      - name: Install dependencies
        run: poetry install -v
      - name: Run unit tests
        run:  poetry run pytest -m unit --cov --cov-branch --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
